
#[Your Marketplace Name]
#url = https://www.yourmarketplace.com
#search = //*[@id="your-search-box-id"]
#products_cards = //*[@class="your-product-card-class"]

#card_name = .//*[@class="your-card-name-class"]
#card_value = .//*[@class="your-card-value-class"]
#card_link = .//*[@class="your-card-link-class"]

#next_page = //*[@class="your-next-page-button-class"]

[Amazon]
url = https://www.amazon.com
search = //*[@class="nav-input nav-progressive-attribute"]
products_cards = //div[@data-component-type='s-search-result']

card_name = .//a[contains(@class, 'a-text-normal')]
card_value = .//span[contains(@class, 'a-price')]/span[contains(@class, 'a-offscreen')]
card_link = .//a[contains(@class, 'a-text-normal')]

next_page = //a[contains(@aria-label, "Go to next page")]

[Mercado Livre]
url = https://www.mercadolivre.com.br/
search = //*[@id="cb1-edit"]
products_cards = //*[@class="ui-search-layout__item"]

card_name = .//*[@class="poly-component__title-wrapper"]
card_value = .//*[@class="andes-money-amount andes-money-amount--cents-superscript"]
card_link = .//*[@class="poly-component__title"]

next_page = //*[@title="Seguinte"]

