
#[Your Marketplace Name]
#url = https://www.yourmarketplace.com
#search = //*[@id="your-search-box-id"]
#products_cards = //*[@class="your-product-card-class"]

#card_name = .//*[@class="your-card-name-class"]
#card_value = .//*[@class="your-card-value-class"]
#card_link = .//*[@class="your-card-link-class"]

#next_page = //*[@class="your-next-page-button-class"]


[Amazon]
url = https://www.amazon.com.br/
search = //*[@placeholder="Pesquisar Amazon.com.br"]
products_cards = //div[@class='a-section a-spacing-small puis-padding-left-small puis-padding-right-small']

card_name = .//*[@class='a-link-normal s-line-clamp-4 s-link-style a-text-normal']
card_value = .//*[@class='a-price']
card_link = .//*[@class='a-link-normal s-line-clamp-4 s-link-style a-text-normal']

next_page = //a[@class='s-pagination-item s-pagination-next s-pagination-button s-pagination-button-accessibility s-pagination-separator']

[Mercado Livre]
url = https://www.mercadolivre.com.br/
search = //*[@id="cb1-edit"]
products_cards = //*[@class="ui-search-layout__item"]

card_name = .//*[@class="poly-component__title-wrapper"]
card_value = .//*[@class="andes-money-amount__fraction"]
card_link = .//*[@class="poly-component__title"]

next_page = //*[@title="Seguinte"]

