[Amazon]
# EM DESENVOLVIMENTO - ELEMENTOS PODEM ESTAR DESATUALIZADOS
search = //*[@id="twotabsearchtextbox"]
products_cards = //*[@class="a-section a-spacing-small puis-padding-left-small puis-padding-right-small"]

card_name = .//*[@class="a-size-medium a-color-base a-text-normal"]
card_value = .//*[@class="a-price"]
card_link = .//*[@class="a-size-medium a-color-base a-text-normal"]/parent::a  

next_page = //*[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]

[Mercado Livre]
search = //*[@id="cb1-edit"]
products_cards = //*[@class="ui-search-layout__item"]

card_name = .//*[@class="poly-component__title-wrapper"]
card_value = .//*[@class="andes-money-amount andes-money-amount--cents-superscript"]
card_link = .//*[@class="poly-component__title-wrapper"]/a

next_page = //*[@title="Seguinte"]

